# Generated by Django 4.2.16 on 2025-08-29 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('data_emissao', models.CharField(max_length=20)),
                ('status', models.CharField(default='ativo', max_length=20)),
            ],
        ),
    ]
